# Generated by Django 4.2.17 on 2025-10-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter_file',
            field=models.FileField(blank=True, help_text='Upload your cover letter (PDF, DOC, DOCX)', null=True, upload_to='cover_letters/'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
    ]
