# Generated by Django 4.2.17 on 2025-10-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_workerprofile_profile_image'),
        ('jobs', '0002_jobapplication_cover_letter_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='assigned_workers',
            field=models.ManyToManyField(blank=True, related_name='assigned_jobs', to='workers.workerprofile'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='workers_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of workers needed for this job'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, help_text='Deprecated: Use assigned_workers instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_assigned_jobs', to='workers.workerprofile'),
        ),
    ]
