# Generated by Django 4.2.17 on 2025-10-21 08:46

from django.db import migrations


def copy_assigned_workers(apps, schema_editor):
    """Copy data from assigned_worker to assigned_workers"""
    JobRequest = apps.get_model('jobs', 'JobRequest')
    
    for job in JobRequest.objects.filter(assigned_worker__isnull=False):
        # Add the single assigned worker to the many-to-many field
        job.assigned_workers.add(job.assigned_worker)


def reverse_copy_assigned_workers(apps, schema_editor):
    """Reverse operation - copy first assigned worker back to assigned_worker"""
    JobRequest = apps.get_model('jobs', 'JobRequest')
    
    for job in JobRequest.objects.filter(assigned_workers__isnull=False):
        # Set assigned_worker to the first worker in assigned_workers
        first_worker = job.assigned_workers.first()
        if first_worker:
            job.assigned_worker = first_worker
            job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobrequest_assigned_workers_and_more'),
    ]

    operations = [
        migrations.RunPython(copy_assigned_workers, reverse_copy_assigned_workers),
    ]
