# Generated by Django 4.2.17 on 2025-12-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_workerdocument_is_required_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0005_add_security_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DirectHireRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of work', max_length=200)),
                ('description', models.TextField(help_text='Detailed work description')),
                ('location', models.CharField(help_text='Where the work will be done', max_length=255)),
                ('duration_type', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=10)),
                ('duration_value', models.PositiveIntegerField(help_text='Number of hours or days')),
                ('start_datetime', models.DateTimeField(help_text='When should the work start?')),
                ('offered_rate', models.DecimalField(decimal_places=2, help_text='Offered hourly/daily rate', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total estimated amount', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('worker_response_message', models.TextField(blank=True, help_text="Worker's response/reason")),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('client_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_hire_requests', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_requests', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='direct_hire',
            field=models.ForeignKey(blank=True, help_text='Link to direct hire request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='jobs.directhirerequest'),
        ),
        migrations.AddIndex(
            model_name='directhirerequest',
            index=models.Index(fields=['worker', 'status'], name='jobs_direct_worker__266534_idx'),
        ),
        migrations.AddIndex(
            model_name='directhirerequest',
            index=models.Index(fields=['client', 'status'], name='jobs_direct_client__8da8d1_idx'),
        ),
        migrations.AddIndex(
            model_name='directhirerequest',
            index=models.Index(fields=['-created_at'], name='jobs_direct_created_4d4f2c_idx'),
        ),
    ]
