# Generated by Django 4.2.17 on 2025-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobapplication_status_alter_jobrequest_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['job'], name='jobs_jobapp_job_id_286de1_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['worker'], name='jobs_jobapp_worker__a34f63_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['status'], name='jobs_jobapp_status_8c3944_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['-created_at'], name='jobs_jobapp_created_9043f9_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['client'], name='jobs_jobreq_client__ec8b58_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status'], name='jobs_jobreq_status_95e94f_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['category'], name='jobs_jobreq_categor_163dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['city'], name='jobs_jobreq_city_4ab860_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['urgency'], name='jobs_jobreq_urgency_a48eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['-created_at'], name='jobs_jobreq_created_27ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status', 'created_at'], name='jobs_jobreq_status_658a30_idx'),
        ),
    ]
