# Generated by Django 4.2.17 on 2025-12-29 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='duration_days',
            field=models.IntegerField(help_text='Estimated duration in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='workers_needed',
            field=models.PositiveIntegerField(default=1, help_text='Number of workers needed for this job', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
