# Generated by Django 4.2.17 on 2026-01-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_batch8_features'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status', 'city', '-created_at'], name='jobs_jobreq_status_c806ef_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['status', 'category'], name='jobs_jobreq_status_121ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrequest',
            index=models.Index(fields=['client', 'status'], name='jobs_jobreq_client__8c8869_idx'),
        ),
    ]
