# Generated by Django 4.2.17 on 2026-02-03 06:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_payment_workerearning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0012_add_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief description of service needed', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of work required')),
                ('location', models.CharField(help_text='Service location address', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred date for service', null=True)),
                ('preferred_time', models.TimeField(blank=True, help_text='Preferred time for service', null=True)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, help_text='Estimated duration in hours', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('status', models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Worker Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('worker_accepted', models.BooleanField(blank=True, help_text='Worker acceptance status', null=True)),
                ('worker_response_at', models.DateTimeField(blank=True, null=True)),
                ('worker_rejection_reason', models.TextField(blank=True)),
                ('work_started_at', models.DateTimeField(blank=True, null=True)),
                ('work_completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by_worker_at', models.DateTimeField(blank=True, help_text='When worker confirmed completion', null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for this service', max_digits=10, null=True)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours worked (from time tracking)', max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount (hours × rate)', max_digits=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes')),
                ('client_notes', models.TextField(blank=True, help_text='Additional notes from client')),
                ('completion_notes', models.TextField(blank=True, help_text="Worker's completion notes")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who assigned the worker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='workers.workerprofile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='workers.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('assigned', 'Assigned to Service'), ('accepted', 'Accepted Assignment'), ('rejected', 'Rejected Assignment'), ('started', 'Started Work'), ('paused', 'Paused Work'), ('resumed', 'Resumed Work'), ('completed', 'Completed Work'), ('cancelled', 'Service Cancelled')], max_length=20)),
                ('description', models.TextField(help_text='Activity description')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('amount_earned', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='jobs.servicerequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='workers.workerprofile')),
            ],
            options={
                'verbose_name_plural': 'Worker Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['worker', '-created_at'], name='jobs_worker_worker__0697c9_idx'), models.Index(fields=['service_request', '-created_at'], name='jobs_worker_service_8806c4_idx'), models.Index(fields=['activity_type', '-created_at'], name='jobs_worker_activit_4b3b6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField(help_text='When worker started work')),
                ('clock_out', models.DateTimeField(blank=True, help_text='When worker finished work', null=True)),
                ('clock_in_location', models.CharField(blank=True, max_length=255)),
                ('clock_out_location', models.CharField(blank=True, max_length=255)),
                ('duration_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated duration in hours', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Work notes, issues encountered, etc.')),
                ('verified_by_client', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='jobs.servicerequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['service_request', '-clock_in'], name='jobs_timetr_service_a110ca_idx'), models.Index(fields=['worker', '-clock_in'], name='jobs_timetr_worker__8ea7e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['client', 'status'], name='jobs_servic_client__e5dba4_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['assigned_worker', 'status'], name='jobs_servic_assigne_2d57ec_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', '-created_at'], name='jobs_servic_status_0e7431_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['category', 'status'], name='jobs_servic_categor_c4deb8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['urgency', 'status'], name='jobs_servic_urgency_5b8ebe_idx'),
        ),
    ]
