# Generated by Django 4.2.17 on 2026-03-03 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_servicerequest_workeractivity_timetracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rate at time of booking', max_digits=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='duration_days',
            field=models.IntegerField(default=1, help_text='Total number of days for service', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='duration_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('3_months', '3 Months'), ('6_months', '6 Months'), ('yearly', 'Yearly'), ('custom', 'Custom Date Range')], default='daily', help_text='Service duration type', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was completed', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method used (fake for demo)', max_length=50),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('failed', 'Payment Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_transaction_id',
            field=models.CharField(blank=True, help_text='Payment transaction ID (fake for demo)', max_length=100),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_end_date',
            field=models.DateField(blank=True, help_text='Service end date (for custom range)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_start_date',
            field=models.DateField(blank=True, help_text='Service start date (for custom range)', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price (daily_rate × duration_days)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DEPRECATED: Use duration_days instead', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
    ]
