# Generated by Django 4.2.17 on 2026-03-08 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0015_servicerequest_cancellation_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='payment_screenshot',
            field=models.ImageField(blank=True, help_text='Payment proof screenshot uploaded by client', null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_verified',
            field=models.BooleanField(default=False, help_text='Admin verified payment screenshot'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, help_text='When payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
