# Generated by Django 4.2.17 on 2026-03-10 05:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workers', '0018_savedcard_mobilemoneyaccount_bankaccount'),
        ('jobs', '0016_add_payment_screenshot_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='workers_needed',
            field=models.IntegerField(default=1, help_text='Number of workers needed for this service (1-100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned the worker(s)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, help_text='LEGACY: First assigned worker (use assignments relation for multiple workers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to='workers.workerprofile'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Daily rate per worker at time of booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price (daily_rate × duration_days × workers_needed)', max_digits=10),
        ),
        migrations.CreateModel(
            name='ServiceRequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_number', models.IntegerField(default=1, help_text='Worker number (e.g., 1 of 3)')),
                ('status', models.CharField(choices=[('pending', 'Pending Worker Response'), ('accepted', 'Accepted by Worker'), ('rejected', 'Rejected by Worker'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Assignment status', max_length=20)),
                ('worker_accepted', models.BooleanField(blank=True, help_text='Worker acceptance status', null=True)),
                ('worker_response_at', models.DateTimeField(blank=True, help_text='When worker responded', null=True)),
                ('worker_rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected')),
                ('work_started_at', models.DateTimeField(blank=True, help_text='When worker started work', null=True)),
                ('work_completed_at', models.DateTimeField(blank=True, help_text='When work was completed', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text="Worker's completion notes")),
                ('worker_payment', models.DecimalField(decimal_places=2, default=0, help_text='Payment amount for this worker (daily_rate × duration)', max_digits=10)),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0, help_text='Total hours this worker spent', max_digits=5)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for this specific assignment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='Admin who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(help_text='The service request this assignment is for', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='jobs.servicerequest')),
                ('worker', models.ForeignKey(help_text='The worker assigned to this service', on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['service_request', 'assignment_number'],
                'indexes': [models.Index(fields=['service_request', 'status'], name='jobs_servic_service_860a90_idx'), models.Index(fields=['worker', 'status'], name='jobs_servic_worker__54258f_idx'), models.Index(fields=['status', '-assigned_at'], name='jobs_servic_status_fad1d7_idx')],
                'unique_together': {('service_request', 'worker')},
            },
        ),
    ]
