# Generated by Django 4.2.30 on 2026-07-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0020_workerprofile_latitude_workerprofile_longitude"),
        ("jobs", "0017_servicerequest_workers_needed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="latitude",
            field=models.FloatField(
                blank=True, help_text="GPS latitude of the service location", null=True
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="longitude",
            field=models.FloatField(
                blank=True, help_text="GPS longitude of the service location", null=True
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="preferred_worker",
            field=models.ForeignKey(
                blank=True,
                help_text="Worker the client requested; admin confirms or picks someone else",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_by_requests",
                to="workers.workerprofile",
            ),
        ),
    ]
