# Generated by Django 4.2.30 on 2026-07-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0018_servicerequest_latitude_servicerequest_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="assignment_mode",
            field=models.CharField(
                choices=[
                    ("admin_choice", "Admin Chooses"),
                    ("client_choice", "Client Chose a Worker"),
                    ("auto_nearest", "Auto-Assigned Nearest"),
                ],
                default="admin_choice",
                help_text="How the worker for this request is meant to be selected",
                max_length=20,
            ),
        ),
    ]
