# Generated by Django 4.2.17 on 2026-08-13 07:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0020_alter_review_reviewer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
