# Generated by Django 4.2.17 on 2026-08-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0021_alter_activity_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedjob",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_by",
                to="jobs.servicerequest",
            ),
        ),
    ]
