# Generated by Django 4.2.17 on 2026-08-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_savedjob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform service fee at time of booking, charged once per request', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Category amount per worker at time of booking', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total price ((daily_rate × workers_needed) + service_fee)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicerequestassignment',
            name='worker_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='What this worker earns for the request (the category amount, once)', max_digits=10),
        ),
    ]
