# Generated by Django 4.2.17 on 2026-08-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_servicerequest_service_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='hourly_rate',
        ),
    ]
