# Generated by Django 4.2.17 on 2026-03-18 08:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, help_text='Business or trading name', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short description about the agent')),
                ('agent_code', models.CharField(blank=True, help_text='Unique code workers use to register under this agent (generated on approval)', max_length=10, null=True, unique=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage earned per job completed by managed workers', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_verified', models.BooleanField(default=False, help_text='Set by admin after reviewing the application')),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_verified'], name='agents_agen_is_veri_1ce776_idx'), models.Index(fields=['agent_code'], name='agents_agen_agent_c_37f78f_idx')],
            },
        ),
    ]
