# Generated by Django 4.2.17 on 2026-08-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worker_connect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("job_assigned", "Job Assigned"),
                    ("job_accepted", "Job Accepted"),
                    ("job_rejected", "Job Rejected"),
                    ("job_completed", "Job Completed"),
                    ("job_application", "Job Application"),
                    ("message_received", "Message Received"),
                    ("payment_received", "Payment Received"),
                    ("review_received", "Review Received"),
                    ("document_verified", "Document Verified"),
                    ("account_update", "Account Update"),
                    ("system_alert", "System Alert"),
                    ("promotion", "Promotion"),
                ],
                max_length=20,
            ),
        ),
    ]
