# Generated by Django 4.2.17 on 2025-12-29 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='total_jobs_posted',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='clients_cli_user_id_f868b5_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['city'], name='clients_cli_city_3cb904_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['client'], name='clients_fav_client__82968a_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['worker'], name='clients_fav_worker__dc3c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['client'], name='clients_rat_client__abd548_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['worker'], name='clients_rat_worker__7cbedb_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rating'], name='clients_rat_rating_c8a6a3_idx'),
        ),
    ]
