# Generated by Django 4.2.17 on 2026-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_validators_and_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100),
        ),
    ]
