# Generated by Django 4.2.17 on 2026-08-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_alter_clientprofile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Brief introduction about the client"
            ),
        ),
    ]
