# Generated by Django 4.2.17 on 2026-08-27 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0023_servicerequest_service_fee_and_more'),
        ('clients', '0004_clientprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('card', 'Card'), ('mpesa', 'Mobile Money')], max_length=20)),
                ('is_demo', models.BooleanField(default=True, help_text='True while payments are simulated; a real gateway sets this False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('consumed_by', models.OneToOneField(blank=True, help_text='The request this reference paid for, once redeemed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reference', to='jobs.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='clients_pay_referen_5385fe_idx'), models.Index(fields=['client', '-created_at'], name='clients_pay_client__a8375b_idx')],
            },
        ),
    ]
