# Generated by Django 4.2.17 on 2026-09-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='method',
            field=models.CharField(choices=[('card', 'Card'), ('yas', 'Mixx by YAS')], max_length=20),
        ),
    ]
