# Generated by Django 4.2.17 on 2025-12-29 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_jobs', models.BooleanField(default=True)),
                ('email_job_applications', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_job_updates', models.BooleanField(default=True)),
                ('email_marketing', models.BooleanField(default=False)),
                ('email_weekly_digest', models.BooleanField(default=True)),
                ('push_new_jobs', models.BooleanField(default=True)),
                ('push_job_applications', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_job_updates', models.BooleanField(default=True)),
                ('push_reminders', models.BooleanField(default=True)),
                ('sms_job_applications', models.BooleanField(default=False)),
                ('sms_urgent_messages', models.BooleanField(default=False)),
                ('email_frequency', models.CharField(choices=[('instant', 'Instant'), ('hourly', 'Hourly Digest'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='instant', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification preferences',
            },
        ),
    ]
