# Generated by Django 4.2.17 on 2026-03-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_batch7_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('client', 'Client'), ('admin', 'Admin'), ('agent', 'Agent')], max_length=10),
        ),
    ]
