# Generated by Django 4.2.17 on 2026-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="allow_search_indexing",
            field=models.BooleanField(
                default=True, help_text="Allow profile to appear in search results"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_analytics",
            field=models.BooleanField(
                default=False, help_text="Consent to usage analytics tracking"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_personalization",
            field=models.BooleanField(
                default=False, help_text="Consent to personalized recommendations"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="consent_third_party_sharing",
            field=models.BooleanField(
                default=False,
                help_text="Consent to sharing data with third-party partners",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(
                default=False, help_text="Show email on public profile"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(
                default=False, help_text="Show phone number on public profile"
            ),
        ),
    ]
