# Generated by Django 4.2.17 on 2025-10-18 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSkillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('category', 'Category'), ('skill', 'Skill')], max_length=20)),
                ('name', models.CharField(help_text='Name of the requested category or skill', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='For skill requests, which category does it belong to?', null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'request_type', 'name', 'category')},
            },
        ),
    ]
