# Generated by Django 4.2.17 on 2025-10-18 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_customskillrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerCustomSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of this skill')),
                ('certificate', models.FileField(blank=True, help_text='Upload certificate (optional)', null=True, upload_to='skill_certificates/')),
                ('years_of_experience', models.IntegerField(default=0, help_text='Years of experience with this skill')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified this skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_skills', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkerCustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What services do you offer in this category?')),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified this category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('worker', 'name')},
            },
        ),
    ]
