# Generated by Django 4.2.17 on 2025-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_workercustomskill_workercustomcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='worker_profiles/'),
        ),
    ]
