# Generated by Django 4.2.17 on 2025-10-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_workerprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='can_work_everywhere',
            field=models.BooleanField(default=False, help_text='Available to work in any location'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='religion',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('islam', 'Islam'), ('christianity', 'Christianity'), ('judaism', 'Judaism'), ('hinduism', 'Hinduism'), ('buddhism', 'Buddhism'), ('sikhism', 'Sikhism'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
