# Generated by Django 4.2.17 on 2025-12-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_add_security_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdocument',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Is this document required for verification?'),
        ),
        migrations.AlterField(
            model_name='workerdocument',
            name='document_type',
            field=models.CharField(choices=[('id', 'ID Card (Required)'), ('cv', 'CV/Resume (Optional)'), ('certificate', 'Certificate (Optional)'), ('license', 'License (Optional)'), ('other', 'Other (Optional)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workerdocument',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
