# Generated by Django 4.2.17 on 2025-12-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_workerdocument_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='has_uploaded_national_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='worker_type',
            field=models.CharField(choices=[('professional', 'Professional'), ('non_academic', 'Non-Academic')], default='non_academic', max_length=20),
        ),
    ]
