# Generated by Django 4.2.17 on 2025-12-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_workerprofile_has_uploaded_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='profile_image',
            field=models.FileField(blank=True, help_text='Profile photo', null=True, upload_to='worker_profiles/'),
        ),
    ]
