# Generated by Django 4.2.17 on 2025-12-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_alter_workerprofile_profile_image'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['user'], name='workers_wor_user_id_2ec0c9_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['verification_status'], name='workers_wor_verific_c00670_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['availability'], name='workers_wor_availab_f5b3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['city'], name='workers_wor_city_9eed10_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['worker_type'], name='workers_wor_worker__c6ebb2_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['is_featured'], name='workers_wor_is_feat_b42e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['average_rating'], name='workers_wor_average_2445fd_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['-created_at'], name='workers_wor_created_62f4f1_idx'),
        ),
    ]
