# Generated by Django 4.2.17 on 2025-12-29 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_batch7_features'),
        ('workers', '0011_add_validators_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_availability', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['worker', 'is_active'], name='workers_rec_worker__b5e5ab_idx'), models.Index(fields=['day_of_week'], name='workers_rec_day_of__fac7f6_idx')],
                'unique_together': {('worker', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='BookedSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to='jobs.jobrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_slots', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['worker', 'date'], name='workers_boo_worker__ef09e7_idx'), models.Index(fields=['status'], name='workers_boo_status_60f1a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('unavailable', 'Unavailable'), ('available', 'Available')], max_length=20)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['worker', 'date'], name='workers_ava_worker__6d3318_idx')],
            },
        ),
    ]
