# Generated by Django 4.2.17 on 2025-12-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workers.portfolio


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_batch8_features'),
        ('workers', '0012_batch7_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('badge_type', models.CharField(choices=[('identity_verified', 'Identity Verified'), ('background_check', 'Background Check'), ('skill_certified', 'Skill Certified'), ('top_rated', 'Top Rated'), ('fast_responder', 'Fast Responder'), ('reliability', 'Reliability Badge'), ('veteran', 'Veteran Worker'), ('premium', 'Premium Member')], max_length=30, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=20)),
                ('requirements', models.TextField(blank=True, help_text='Human-readable requirements')),
                ('auto_award', models.BooleanField(default=False, help_text='Automatically awarded when criteria met')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VerificationTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField()),
                ('min_reviews', models.PositiveIntegerField(default=0)),
                ('min_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('min_completed_jobs', models.PositiveIntegerField(default=0)),
                ('benefits', models.TextField(blank=True, help_text='JSON list of benefits')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Platform commission percentage', max_digits=5)),
                ('priority_in_search', models.BooleanField(default=False)),
                ('badge_color', models.CharField(default='#6c757d', max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('required_badges', models.ManyToManyField(blank=True, related_name='required_for_tiers', to='workers.verificationbadge')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('link', 'External Link')], default='image', max_length=20)),
                ('media_file', models.FileField(blank=True, null=True, upload_to=workers.portfolio.portfolio_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/')),
                ('external_url', models.URLField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.category')),
                ('related_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobrequest')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-is_featured', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='badge_verifications/')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='workers.verificationbadge')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_verified', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-issued_at'],
                'unique_together': {('worker', 'badge')},
            },
        ),
    ]
