# Generated by Django 4.2.17 on 2026-01-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0013_batch8_features'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['verification_status', 'availability', '-average_rating'], name='workers_wor_verific_e0bb48_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['city', 'verification_status'], name='workers_wor_city_7c757d_idx'),
        ),
        migrations.AddIndex(
            model_name='workerprofile',
            index=models.Index(fields=['verification_status', '-created_at'], name='workers_wor_verific_96a2ae_idx'),
        ),
    ]
