# Generated by Django 4.2.17 on 2026-03-03 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0015_payment_workerearning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Daily rate in USD for this service category', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
