# Generated by Django 4.2.17 on 2026-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0016_category_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100),
        ),
    ]
