# Generated by Django 4.2.17 on 2026-03-18 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('workers', '0018_savedcard_mobilemoneyaccount_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent who recruited this worker (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='agents.agentprofile'),
        ),
    ]
