# Generated by Django 4.2.30 on 2026-07-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0019_workerprofile_agent"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="GPS latitude, for nearest-worker matching",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="GPS longitude, for nearest-worker matching",
                null=True,
            ),
        ),
    ]
