# Generated by Django 4.2.17 on 2026-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0020_workerprofile_latitude_workerprofile_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="verification_tier",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Verification tier level (see workers.badges.VerificationTier)",
            ),
        ),
    ]
