# Generated by Django 4.2.17 on 2026-08-10 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0021_workerprofile_verification_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="total_reviews",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
