# Generated by Django 4.2.17 on 2026-08-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0022_workerprofile_total_reviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="is_public",
            field=models.BooleanField(
                default=True,
                help_text="Whether this worker's profile is visible to clients browsing/searching",
            ),
        ),
    ]
