# Generated by Django 4.2.17 on 2026-08-13 07:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0023_workerprofile_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
            ),
        ),
    ]
