# Generated by Django 4.2.17 on 2026-08-27 18:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0024_alter_payment_metadata_alter_payment_provider_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform service fee added once per request (TSh). Defaults to 0 so adding this column never silently reprices existing categories - set the real fee per category in the admin.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='category',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=25.0, help_text='Amount charged per worker for one request in this category (TSh). Pricing is per request, not per day - the field keeps its original name because the API and the released mobile app read it.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
