# Generated by Django 4.2.17 on 2026-08-31 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0025_category_service_fee_alter_category_daily_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='hourly_rate',
        ),
    ]
